trigger:
  branches:
    include:
    - master
  paths:
    exclude:
      - .azure-pipelines/release.yml
      - README.md

pr: none

stages:
  - stage: 'build'
    displayName: 'Build'
    jobs:   
      - job: 'linux'
        displayName: 'Linux'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-linux.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathToPublish: "binaries-*-linux.zip"
              ArtifactName: 'linux-artifacts'
            displayName: 'Publish Linux Artifacts'
      - job: 'osx'
        displayName: 'OSX'
        pool:
          vmImage: 'macos-latest'
        steps:
          - checkout: self
            fetchDepth: 1
          - template: templates/build-osx.yml
          - task: PublishBuildArtifacts@1
            inputs:
              PathToPublish: "binaries-*-osx.zip"
              ArtifactName: 'osx-artifacts'
            displayName: 'Publish OSX Artifacts'